export const SOURCES = [
  { id: 'zighang', name: '직행', note: '서울·경기 간호사 엄격 필터', method: '8페이지 JSON API', scope: '간호사 제목 확인·중복 제거', collection: 'auto', color: '#17211d', url: 'https://zighang.com/' },
  { id: 'nurscape', name: '너스케입', note: '간호사 전문 채용', method: '15페이지 Chrome 브리지', scope: '매일 09·12·18시 동기화', collection: 'bridge', color: '#3968d6', url: 'https://recruit.nurscape.net/Jobs/List' },
  { id: 'nurselink', name: '널스링크', note: '산업간호사 전용', method: '목록 HTML', scope: '산업간호사', collection: 'auto', color: '#e09b22', url: 'https://nurse-link.co.kr/jobs?jobCategoryIds=26' },
  { id: 'rnjob', name: 'RNJOB', note: '대한간호협회', method: 'SSO + HTML', scope: '간호사·보건관리자', collection: 'auto', color: '#12816b', url: 'https://rnjob.koreanursing.or.kr/' },
  { id: 'medicaljob', name: '메디컬잡', note: '상근·외래·검진·CRC', method: '4개 제목 검색', scope: '비교대 간호 검색어', collection: 'auto', color: '#3874a8', url: 'https://www.medicaljob.co.kr/job/' },
  { id: 'hospitaljob', name: '병원잡', note: '중소병원·요양기관', method: '목록 HTML', scope: '병원 간호직', collection: 'auto', color: '#287f91', url: 'https://www.byeongwonjob.com/cms/s01.php' },
  { id: 'kaohn', name: '직업건강협회', note: '보건관리자 구인', method: '게시판 HTML', scope: '보건관리자', collection: 'auto', color: '#25845d', url: 'https://www.kaohn.or.kr/board/bbs81_1' },
  { id: 'kisanhyup', name: '산업보건협의회', note: '기업 산업보건', method: '게시판 HTML', scope: '산업보건', collection: 'auto', color: '#3f6958', url: 'https://kisanhyup.co.kr/bbs/board.php?bo_table=bd_num7' },
  { id: 'saramin', name: '사람인', note: '보건관리·상근·외래·검진·CRC', method: '검색 HTML', scope: '6개 간호 검색어', collection: 'auto', color: '#ef5b32', url: 'https://www.saramin.co.kr/zf_user/search?searchType=search&searchword=%EC%83%81%EA%B7%BC%20%EA%B0%84%ED%98%B8%EC%82%AC' },
  { id: 'indeed', name: 'Indeed', note: '최근 14일 상근직 간호사', method: '원문 바로가기', scope: '상근직·주간 간호', collection: 'link', color: '#2557a7', url: 'https://kr.indeed.com/jobs?q=%EC%83%81%EA%B7%BC%EC%A7%81+%EA%B0%84%ED%98%B8%EC%82%AC&fromage=14&sort=date' },
  { id: 'jobkorea', name: '잡코리아', note: '기업 보건관리자', method: '검색 HTML', scope: '보건관리자', collection: 'auto', color: '#2c6de9', url: 'https://www.jobkorea.co.kr/Search/?stext=%EB%B3%B4%EA%B1%B4%EA%B4%80%EB%A6%AC%EC%9E%90' },
  { id: 'catch', name: '캐치', note: '대기업·공채', method: '검색 HTML', scope: '보건관리자', collection: 'auto', color: '#7757d8', url: 'https://www.catch.co.kr/Search/SearchList?Keyword=%EB%B3%B4%EA%B1%B4%EA%B4%80%EB%A6%AC%EC%9E%90' },
  { id: 'work24', name: '고용24', note: '공식 API 우선 · 최근 2주', method: 'Open API', scope: '상근·외래·검진·CRC·연구·산업간호', collection: 'auto', color: '#e05a33', url: 'https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do' },
  { id: 'wanted', name: '원티드', note: '기업 EHS 경력직', method: '검색 JSON API', scope: '보건관리자·간호사·산업간호·EHS', collection: 'auto', color: '#3979e7', url: 'https://www.wanted.co.kr/search?query=%EB%B3%B4%EA%B1%B4%EA%B4%80%EB%A6%AC%EC%9E%90&tab=position' },
  { id: 'alio', name: 'JOB-ALIO', note: '공공병원·기관', method: '검색 HTML', scope: '보건관리자', collection: 'auto', color: '#7b4f9d', url: 'https://job.alio.go.kr/recruit.do' },
  { id: 'nursejob', name: '널스잡', note: '간호·의료 전문', method: '신규 10페이지 HTML', scope: '최대 500개 간호직', collection: 'auto', color: '#176b55', url: 'https://www.nursejob.co.kr/recruit/list.php?tch=nurse&m=new' },
  { id: 'snuh', name: '서울대병원', note: '간호직 자체 채용', method: '채용 HTML', scope: '간호직', collection: 'auto', color: '#ad3d48', url: 'https://recruit.snuh.org/main.do' },
  { id: 'snubh', name: '분당서울대병원', note: '간호직 자체 채용', method: 'Recruiter POST', scope: '간호직', collection: 'auto', color: '#406a87', url: 'https://snubh.recruiter.co.kr/' },
  { id: 'amc', name: '서울아산병원', note: '부서별 간호 채용', method: '채용 HTML', scope: '간호직', collection: 'auto', color: '#16728a', url: 'https://recruit.amc.seoul.kr/recruit/main.do' },
  { id: 'samsung', name: '삼성서울병원', note: '신입·경력 간호', method: '채용 HTML', scope: '간호직', collection: 'auto', color: '#246ab4', url: 'https://www.samsunghospital.com/home/recruit/main.do' },
  { id: 'ncc', name: '국립암센터', note: '간호·연구 채용', method: 'Recruiter POST', scope: '간호·연구직', collection: 'auto', color: '#5a7e43', url: 'https://ncc.recruiter.co.kr/' },
  { id: 'cmc', name: '가톨릭의료원', note: '서울·경기 6개 성모병원', method: '6개 기관 HTML', scope: '외래·검진·전담 간호', collection: 'auto', color: '#9e4451', url: 'https://recruit.cmcnu.or.kr/' },
  { id: 'smartnurse', name: '스마트널스', note: '신규간호사 공채 일정', method: '원문 바로가기', scope: '신규 간호사', collection: 'link', color: '#ef7667', url: 'https://www.smartnurse.co.kr/recruitmentnews/' },
  { id: 'casemanager', name: '보험심사간호사회', note: '심사간호사 전문 구인', method: '게시판 HTML', scope: '보험심사 간호사', collection: 'auto', color: '#486b8a', url: 'https://www.casemanager.or.kr/bbs/board.php?bo_table=recruit_people' },
  { id: 'snu-nursing', name: '서울대 간호대학', note: '연구·간호 채용 게시판', method: '원문 바로가기', scope: '연구·간호직', collection: 'link', color: '#8c2f39', url: 'https://nursing.snu.ac.kr/board/job-openings' },
  { id: 'yonsei-wonju-nursing', name: '연세대 원주간호', note: '전국 병원 취업자료', method: '원문 바로가기', scope: '간호직', collection: 'link', color: '#174f9a', url: 'https://nursing.yonsei.ac.kr/board/employment_data' },
  { id: 'yuhs', name: '연세의료원', note: '세브란스 통합 채용', method: 'Recruiter POST', scope: '외래·검진·상담·전담', collection: 'auto', color: '#1f5fa8', url: 'https://yuhs.recruiter.co.kr/' },
  { id: 'eumc', name: '이화의료원', note: '목동·서울병원 통합', method: '채용 JSON API', scope: '외래·검진·상담·전담', collection: 'auto', color: '#1f7c64', url: 'https://eumc.applyin.co.kr/' },
  { id: 'paik', name: '백병원', note: '인제대 백병원 통합', method: 'Recruiter POST', scope: '간호사·보건관리 제목 확인', collection: 'auto', color: '#366f9b', url: 'https://paik.recruiter.co.kr/' },
  { id: 'hallym', name: '한림대의료원', note: '성심병원 통합 채용', method: '채용 목록 HTML', scope: '간호사·보건관리 제목 확인', collection: 'auto', color: '#b64a45', url: 'https://recruit.hallym.or.kr/' },
  { id: 'gilhospital', name: '가천대 길병원', note: '신입·경력 간호 채용', method: '원문 바로가기', scope: '간호직', collection: 'link', color: '#3d7f67', url: 'https://gilhospital.recruiter.co.kr/appsite/company/index' },
  { id: 'khmc', name: '경희의료원', note: '간호·보험심사 채용', method: '채용 HTML', scope: '외래·검진·상담·전담', collection: 'auto', color: '#8b6339', url: 'https://recruit.incruit.com/khmc/job/' },
  { id: 'ajich', name: '아주대요양병원', note: '간호·요양 전문 채용', method: '원문 바로가기', scope: '간호직', collection: 'link', color: '#416b91', url: 'https://www.ajich.or.kr/web/notice/recruit' },
  { id: 'bohun', name: '보훈의료공단', note: '보훈병원·요양원 채용', method: '제목 검색 POST', scope: '최근 3주 간호·보건직 원공고', collection: 'auto', color: '#587044', url: 'https://www.bohun.or.kr/main/na/ntt/selectNttList.do?bbsId=1158&mi=37030&rcrut=medical' },
  { id: 'nmc', name: '국립중앙의료원', note: '공공의료 간호 채용', method: '채용판 제목 검색', scope: '접수 중 간호사·간호직', collection: 'auto', color: '#326b78', url: 'https://www.nmc.or.kr/nmc/board/B0000007/' },
  { id: 'kuh', name: '건국대병원', note: '간호·연구직 채용', method: '채용 HTML', scope: '간호 관련 전체', collection: 'auto', color: '#657847', url: 'https://www.kuh.ac.kr/recruit/apply/noticeList.do' },
  { id: 'kumc', name: '고려대의료원', note: '안암·구로·안산 통합', method: 'Jobflex JSON API', scope: '외래·검진·상담·전담', collection: 'auto', color: '#8d3441', url: 'https://kumc.recruiter.co.kr/career/home' },
  { id: 'nursenet', name: '널스넷', note: '간호사 전문 채용', method: '3페이지 목록 HTML', scope: '간호사·보건관리 제목 확인', collection: 'auto', color: '#0d9488', url: 'https://nursenet.co.kr/jobs' },
  { id: 'smc', name: '서울의료원', note: '서울시립 공공병원', method: 'Jobflex JSON API', scope: '간호사·보건관리 제목 확인', collection: 'auto', color: '#2f5d8a', url: 'https://smc.recruiter.co.kr/career/home' },
  { id: 'incruit', name: '인크루트', note: '간호사·보건관리자 검색', method: '키워드 검색 HTML', scope: '간호사·보건관리자 제목 확인', collection: 'auto', color: '#5b21b6', url: 'https://job.incruit.com/' },
];

export function sourceMeta(name) {
  return SOURCES.find((source) => source.name === name) || {
    id: String(name || '').toLowerCase(),
    name,
    note: '채용 원문',
    method: '원문 확인',
    scope: '채용 공고',
    collection: 'link',
    color: '#49665d',
    url: '#',
  };
}
